### ISSUE TITLE
Streamtape Uploader 

### ISSUE THREAD

**Issue by ipoicfrgbg** [DebiprasadXD/streamtape-downloader#1]
hello ,
can u make a Streamtape Uploader bot too thanks.

**Comment by debiplobi** [comment]
okay man, will do that, thanks for the feedback🙂

**Comment by debiplobi** [comment]
You can check this I've included streamtape downloading, uploading capabilities  etc on a bot. [repo](https://github.com/DebiprasadXD/link-media-scraper-bot) @ipoicfrgbg
